### ISSUE TITLE
Cant shut down computer

### ISSUE THREAD

**Issue by IMDEpicGamer** [andro2157/DiscordTokenProtector#9]
It started happening after I installed the program, I also can't use task manager (processes don't load), what do i do
Edit: it says i could lose unsaved work (after i close all programs)

**Comment by IMDEpicGamer** [comment]
Now I can't sign in (the lock screen is blank)
I didnt read the readme text file and assumed I just had to run the batch file (my fault), but now my computer wont work properly and idk how to fix it. i didnt realize i had to compile it

**Comment by IMDEpicGamer** [comment]
I know i messed up but how did me not compiling it lead to this wtf

**Comment by andro2157** [comment]
Hello,

Could you tell me the specs of your computer ?

For the shutdown problem, does it show what program is still running? If it's the protector, it should close automatically, else you can safely force the shutdown.

For the task manager issue, it might be due to a high CPU usage, does that happen when you run the protector ?

For the installation, you just needed to run the batch script, no need to compile it. All it does is copying the needed files in `%appdata%\DiscordTokenProtector`.
I don't see why copying files would lead to the issues your facing.

Have you installed something else?
Can you tell me what antivirus you're using?

**Comment by IMDEpicGamer** [comment]
Nevermind, i just needed to force restart my computer, ill come back if it happens again, thanks
